# Generated by Django 2.0.5 on 2018-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artivle',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
