# Generated by Django 2.0.5 on 2018-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0003_auto_20180507_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artivle',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
