# Generated by Django 2.0.5 on 2018-05-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
