# Generated by Django 2.0.5 on 2018-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_name', models.CharField(max_length=50)),
                ('vote_type', models.IntegerField()),
                ('vote_state', models.IntegerField()),
                ('vote_description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('option_size', models.IntegerField()),
                ('option_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
