# Generated by Django 2.0.5 on 2018-05-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0009_auto_20180510_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='identity',
        ),
        migrations.AddField(
            model_name='entry',
            name='condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_checkable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
