# Generated by Django 2.0.5 on 2018-05-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0010_auto_20180510_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('selection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('simple_detail', models.TextField(null=True)),
                ('detail', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vote_selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startvote.Selection')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startvote.Vote')),
            ],
        ),
    ]
