# Generated by Django 2.0.5 on 2018-05-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0011_selection_vote_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_target',
            field=models.TextField(null=True),
        ),
    ]
