# Generated by Django 2.0.5 on 2018-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0013_auto_20180608_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
