# Generated by Django 2.0.5 on 2018-06-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0015_auto_20180608_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_type',
            new_name='vote_options_num',
        ),
    ]
