# Generated by Django 2.0.5 on 2018-06-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0016_auto_20180612_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_options_num',
            new_name='vote_optionable_num',
        ),
    ]
