# Generated by Django 2.0.5 on 2018-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0017_auto_20180612_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
