# Generated by Django 2.0.5 on 2018-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0018_auto_20180614_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_img',
            field=models.ImageField(null=True, upload_to='pic_folder/'),
        ),
    ]
