# Generated by Django 2.0.5 on 2018-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0019_vote_vote_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_anonymity',
            field=models.BooleanField(default=True),
        ),
    ]
