# Generated by Django 2.0.5 on 2018-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0020_vote_vote_anonymity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_img',
            field=models.ImageField(default='/static/img/2.png', null=True, upload_to='pic_folder/'),
        ),
    ]
