# Generated by Django 2.0.5 on 2018-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startvote', '0024_auto_20180614_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='img',
            field=models.ImageField(default='default/头像.jpeg', upload_to='pic_folder/'),
        ),
    ]
